FROM node:alpine AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable 

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++

COPY package*.json .
COPY pnpm-lock.yaml .
RUN pnpm install

COPY . .

RUN pnpm build

RUN pnpm prune

FROM node:alpine AS production

COPY --from=builder /usr/src/app/.next/standalone ./
COPY --from=builder /usr/src/app/.next/static ./.next/static
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/next.config.mjs ./next.config.mjs
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/pnpm-lock.yaml ./pnpm-lock.yaml

CMD ["node", "server.js"]