name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} << 'EOF'
            # Clone the repository if it hasn't been cloned yet
            if [ ! -d "/var/www/instagram-clone" ]; then
              mkdir -p /var/www/instagram-clone
              git clone git@github.com:shelllbyyyyyy/instagram-clone.git /var/www/instagram-clone
            fi
            
            cd /var/www/instagram-clone
            git pull origin main   # Pull the latest changes from GitHub

            echo "PORT=${{ secrets.BACKEND_PORT }}" >> ./backend/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> ./backend/.env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> ./backend/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./backend/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./backend/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./backend/.env
            echo "DB_REDIS_HOST=${{ secrets.DB_REDIS_HOST }}" >> ./backend/.env
            echo "DB_REDIS_PORT=${{ secrets.DB_REDIS_PORT }}" >> ./backend/.env
            echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> ./backend/.env
            echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> ./backend/.env

            echo "PORT=${{ secrets.FRONTEND_PORT }}" >> ./frontend/.env
            echo "HOST=${{ secrets.FRONTEND_HOST }}" >> ./frontend/.env

            docker compose down       
            docker compose up -d       
          EOF
